### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by marcospereira** [comment]
Hey @lrytz, 

This repository just holds the generated documentation that is published at playframework.com, but it is not the source of that docs (see more information at the [README.md here](https://github.com/playframework/play-generated-docs/blob/master/README.md).

So, the page you made the correction is here:

https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md

Apparently, the typo was already corrected.

Thanks.

**Comment by lrytz** [comment]
ah, sorry, thanks!

**Comment by marcospereira** [comment]
No problem.

Feel free to submit new pull requests when you find other typos. ;-)

Thanks.

**Comment by lrytz** [comment]
(probably this has been said before, but it's a bit unfortunate that the documentation not updated when a fix is pushed to the repo)

**Pull request closed without merging**
